const OPEN_FREE_MAP_SOURCE = 'https://tiles.openfreemap.org/planet';
const OPEN_FREE_MAP_GLYPHS = 'https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf';

const labelText = ['coalesce', ['get', 'name_en'], ['get', 'name']];

const roadWidth = (low, high) => [
  'interpolate', ['exponential', 1.35], ['zoom'],
  5, low,
  15, high,
];

export default function createMinimalStyle() {
  return {
    version: 8,
    name: 'WaterPath Minimal',
    sources: {
      openmaptiles: {
        type: 'vector',
        url: OPEN_FREE_MAP_SOURCE,
        attribution: '&copy; <a href="https://openfreemap.org/">OpenFreeMap</a> &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
      },
    },
    glyphs: OPEN_FREE_MAP_GLYPHS,
    layers: [
      {
        id: 'background',
        type: 'background',
        paint: { 'background-color': '#F6F9FB' },
      },
      {
        id: 'landcover-wood',
        type: 'fill',
        source: 'openmaptiles',
        'source-layer': 'landcover',
        filter: ['match', ['get', 'class'], ['wood', 'grass'], true, false],
        paint: {
          'fill-color': ['match', ['get', 'class'], 'wood', '#D8E8D9', '#E8EFDA'],
          'fill-opacity': ['interpolate', ['linear'], ['zoom'], 4, 0.4, 10, 0.7],
        },
      },
      {
        id: 'landuse-park',
        type: 'fill',
        source: 'openmaptiles',
        'source-layer': 'landuse',
        filter: ['match', ['get', 'class'], ['park', 'cemetery', 'pitch'], true, false],
        paint: { 'fill-color': '#DCECDD', 'fill-opacity': 0.65 },
      },
      {
        id: 'landuse-residential',
        type: 'fill',
        source: 'openmaptiles',
        'source-layer': 'landuse',
        minzoom: 7,
        filter: ['==', ['get', 'class'], 'residential'],
        paint: { 'fill-color': '#EEF2F5', 'fill-opacity': 0.75 },
      },
      {
        id: 'water',
        type: 'fill',
        source: 'openmaptiles',
        'source-layer': 'water',
        paint: { 'fill-color': '#B7D7EF' },
      },
      {
        id: 'waterway',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'waterway',
        minzoom: 7,
        paint: {
          'line-color': '#71AFCA',
          'line-width': ['interpolate', ['linear'], ['zoom'], 7, 0.35, 14, 1.5],
          'line-opacity': 0.85,
        },
      },
      {
        id: 'road-minor',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        minzoom: 11,
        filter: ['match', ['get', 'class'], ['minor', 'service', 'track'], true, false],
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: { 'line-color': '#FFFFFF', 'line-width': roadWidth(0.2, 3) },
      },
      {
        id: 'road-secondary',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        minzoom: 7,
        filter: ['match', ['get', 'class'], ['secondary', 'tertiary'], true, false],
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: { 'line-color': '#FFFFFF', 'line-width': roadWidth(0.4, 5) },
      },
      {
        id: 'road-major',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        minzoom: 5,
        filter: ['match', ['get', 'class'], ['motorway', 'trunk', 'primary'], true, false],
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-color': '#D8C98D',
          'line-width': roadWidth(0.5, 7),
          'line-opacity': 0.9,
        },
      },
      {
        id: 'boundary-region',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'boundary',
        minzoom: 5,
        filter: ['all', ['>=', ['get', 'admin_level'], 3], ['<=', ['get', 'admin_level'], 6], ['!=', ['get', 'maritime'], 1]],
        paint: {
          'line-color': '#96A5AD',
          'line-dasharray': [2, 2],
          'line-width': ['interpolate', ['linear'], ['zoom'], 5, 0.35, 12, 1],
          'line-opacity': 0.65,
        },
      },
      {
        id: 'boundary-country',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'boundary',
        filter: ['all', ['==', ['get', 'admin_level'], 2], ['!=', ['get', 'maritime'], 1]],
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-color': '#5F7380',
          'line-width': ['interpolate', ['linear'], ['zoom'], 2, 0.7, 10, 1.6],
          'line-opacity': 0.85,
        },
      },
      {
        id: 'water-label',
        type: 'symbol',
        source: 'openmaptiles',
        'source-layer': 'water_name',
        minzoom: 4,
        layout: {
          'text-field': labelText,
          'text-font': ['Noto Sans Italic'],
          'text-size': ['interpolate', ['linear'], ['zoom'], 4, 10, 10, 13],
          'text-max-width': 8,
        },
        paint: {
          'text-color': '#488ECF',
          'text-halo-color': '#F6F9FB',
          'text-halo-width': 1.2,
        },
      },
      {
        id: 'road-label',
        type: 'symbol',
        source: 'openmaptiles',
        'source-layer': 'transportation_name',
        minzoom: 12,
        filter: ['match', ['get', 'class'], ['motorway', 'trunk', 'primary', 'secondary'], true, false],
        layout: {
          'symbol-placement': 'line',
          'text-field': labelText,
          'text-font': ['Noto Sans Regular'],
          'text-size': 11,
          'text-rotation-alignment': 'map',
        },
        paint: {
          'text-color': '#53636C',
          'text-halo-color': '#FFFFFF',
          'text-halo-width': 1.5,
        },
      },
      {
        id: 'place-town',
        type: 'symbol',
        source: 'openmaptiles',
        'source-layer': 'place',
        minzoom: 7,
        filter: ['match', ['get', 'class'], ['town', 'village'], true, false],
        layout: {
          'text-field': labelText,
          'text-font': ['Noto Sans Regular'],
          'text-size': ['interpolate', ['linear'], ['zoom'], 7, 10, 12, 12],
          'text-max-width': 8,
        },
        paint: {
          'text-color': '#253B45',
          'text-halo-color': '#FFFFFF',
          'text-halo-width': 1.2,
        },
      },
      {
        id: 'place-city',
        type: 'symbol',
        source: 'openmaptiles',
        'source-layer': 'place',
        minzoom: 4,
        filter: ['==', ['get', 'class'], 'city'],
        layout: {
          'text-field': labelText,
          'text-font': ['Noto Sans Regular'],
          'text-size': ['interpolate', ['linear'], ['zoom'], 4, 11, 10, 15],
          'text-max-width': 8,
        },
        paint: {
          'text-color': '#0D2834',
          'text-halo-color': '#FFFFFF',
          'text-halo-width': 1.4,
        },
      },
      {
        id: 'place-state',
        type: 'symbol',
        source: 'openmaptiles',
        'source-layer': 'place',
        minzoom: 4,
        maxzoom: 9,
        filter: ['==', ['get', 'class'], 'state'],
        layout: {
          'text-field': labelText,
          'text-font': ['Noto Sans Italic'],
          'text-size': ['interpolate', ['linear'], ['zoom'], 4, 10, 8, 13],
          'text-letter-spacing': 0.08,
          'text-transform': 'uppercase',
        },
        paint: {
          'text-color': '#53636C',
          'text-halo-color': '#F6F9FB',
          'text-halo-width': 1.3,
        },
      },
      {
        id: 'place-country',
        type: 'symbol',
        source: 'openmaptiles',
        'source-layer': 'place',
        minzoom: 1,
        maxzoom: 8,
        filter: ['==', ['get', 'class'], 'country'],
        layout: {
          'text-field': labelText,
          'text-font': ['Noto Sans Bold'],
          'text-size': ['interpolate', ['linear'], ['zoom'], 2, 10, 6, 16],
          'text-max-width': 7,
          'text-letter-spacing': 0.06,
        },
        paint: {
          'text-color': '#0B4159',
          'text-halo-color': '#FFFFFF',
          'text-halo-width': 1.5,
        },
      },
    ],
  };
}